### ISSUE TITLE
Strange piece sacrifices for no apparent reason?

### ISSUE THREAD

**Issue by vibranium21** [vibranium21/Bot-chocolate#1]
a big takeaway from a few test games: https://lichess.org/study/wRLbZWZU was that the bot plays solidly, until a MASSIVE, pointless blunder. Trying to figure it out.

**Comment by Virinas-code** [comment]
Horizon effect. He thinks he will get a lot of material after you take his queen back, but you just take back again so he loses at the end.

https://www.chessprogramming.org/Horizon_Effect

**Comment by vibranium21** [comment]
It seems adding a quienscence search really hellped with this issue.
Thanky you for diagnosing the issue!
