### ISSUE TITLE
Checkmate Eval?

### ISSUE THREAD

**Issue by vibranium21** [vibranium21/Bot-chocolate#4]
Bot needs checkmate eval, having trouble implementing.

**Comment by Virinas-code** [comment]
Hmmm, are you using python-chess? I think there is a `ischeckmate()` function.

**Comment by vibranium21** [comment]
Ty! Btw, https://www.youtube.com/post/UgkxFH_Mz3hNaymMgunEfE7ayoX_v5cksoZT I think entering this would be a great way for me to learn microsoft Java. Looking at it I though you'd be interested.
